datasets:
- ca-ab.yaml
- ca-bc.yaml
- ca-mb.yaml
- ca-nb.yaml
- ca-nl.yaml
- ca-ns.yaml
- ca-on.yaml
- ca-pe.yaml
- ca-qc.yaml
- ca-sk.yaml

sheets:
- name: Deaths
  type: timeseries
  timeseries: items
  value: death

- name: Medical
  type: datasheet
  values:
  - key: icu_hospitals
    name: ICU Hospitals
  - key: icu_beds
    name: ICU Beds
  - key: icu_ventalators
    name: ICU Ventalators
  - key: icu_hfov
    name: ICU HFOV
  - key: icu_hospitals_ino
    name: ICU INO
  - key: icu_hospitals_ecmo
    name: ICU ECMO
  - key: spending_pp
    name: Spending (PP)
  - key: doctors_pp
    name: Doctors (PTP)
    multiply: 1000

